# Generated automatically from Makefile.in by configure.
# KDE tags expanded automatically by am_edit - $Revision: 1.3 $ 
# Makefile.in generated automatically by automake 1.4-p6 from Makefile.am

# Copyright (C) 1994, 1995-8, 1999, 2001 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.

####### kdevelop will overwrite this part!!! (begin)##########


SHELL = /bin/sh

srcdir = .
top_srcdir = ..
prefix = /usr
exec_prefix = ${prefix}
#>- 
bindir = ${exec_prefix}/bin
#>+ 3
DEPDIR = .deps

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DESTDIR =

pkgdatadir = $(datadir)/kmd
pkglibdir = $(libdir)/kmd
pkgincludedir = $(includedir)/kmd

top_builddir = ..

ACLOCAL = aclocal-1.4
AUTOCONF = autoconf
AUTOMAKE = automake-1.4
AUTOHEADER = autoheader

INSTALL = /usr/bin/install -c -p
INSTALL_PROGRAM = ${INSTALL} $(INSTALL_STRIP_FLAG) $(AM_INSTALL_PROGRAM_FLAGS)
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL}
transform = s,x,x,

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_alias = i686-pc-linux-gnu
build_triplet = i686-pc-linux-gnu
host_alias = i686-pc-linux-gnu
host_triplet = i686-pc-linux-gnu
target_alias = i686-pc-linux-gnu
target_triplet = i686-pc-linux-gnu
ARTSCCONFIG = /usr/bin/artsc-config
AS = @AS@
AUTODIRS = 
CC = gcc
CONF_FILES =  $(top_srcdir)/./admin/configure.in.min $(top_srcdir)/configure.in.in $(top_srcdir)/./kmd-0.2/configure.in.in
CPP = gcc -E
CXX = c++
CXXCPP = c++ -E
DCOPIDL = /usr/bin/dcopidl
DCOPIDL2CPP = /usr/bin/dcopidl2cpp
DCOP_DEPENDENCIES = $(DCOPIDL)
DLLTOOL = @DLLTOOL@
DPMSINC = @DPMSINC@
DPMSLIB = @DPMSLIB@
EXEEXT = 
GCJ = @GCJ@
GCJFLAGS = @GCJFLAGS@
GLINC = @GLINC@
GLLIB = @GLLIB@
GMSGFMT = /usr/bin/msgfmt
IDL = @IDL@
IDL_DEPENDENCIES = @IDL_DEPENDENCIES@
JAR = @JAR@
JAVAC = @JAVAC@
JAVAH = @JAVAH@
JVMLIBS = @JVMLIBS@
KDECONFIG = /usr/bin/kde-config
KDE_CXXFLAGS = 
KDE_EXTRA_RPATH = 
KDE_INCLUDES = -I/usr/include/kde
KDE_LDFLAGS = -L/usr/lib
KDE_MT_LDFLAGS = 
KDE_MT_LIBS = -lpthread
KDE_PLUGIN = -avoid-version -module -no-undefined $(KDE_RPATH) $(KDE_MT_LDFLAGS)
KDE_RPATH = -R $(kde_libraries) -R $(x_libraries)
KDE_USE_CLOSURE_FALSE = #
KDE_USE_CLOSURE_TRUE = 
KDE_USE_FINAL_FALSE = 
KDE_USE_FINAL_TRUE = #
KDE_XSL_STYLESHEET = /usr/share/apps/ksgmltools2/customization/kde-chunk.xsl
LEX = @LEX@
LEXLIB = @LEXLIB@
LIBCOMPAT = 
LIBCRYPT = -lcrypt
LIBDL = -ldl
LIBGEN = @LIBGEN@
LIBJPEG = -ljpeg
LIBMICO = @LIBMICO@
LIBOBJS = @LIBOBJS@
LIBPNG = -lpng -lz -lm
LIBPTHREAD = -lpthread
LIBPYTHON = @LIBPYTHON@
LIBQIMGIO = @LIBQIMGIO@
LIBRESOLV = -lresolv
LIBSHADOW = @LIBSHADOW@
LIBSM = -lSM -lICE
LIBSOCKET =  -lresolv
LIBTIFF = @LIBTIFF@
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIBUCB = 
LIBUTIL = -lutil
LIBXINERAMA = 
LIBZ = -lz
LIB_KAB = -lkab
LIB_KDECORE = -lkdecore
LIB_KDEPRINT = -lkdeprint
LIB_KDEUI = -lkdeui
LIB_KFILE = -lkio
LIB_KFM = 
LIB_KHTML = -lkhtml
LIB_KIMGIO = @LIB_KIMGIO@
LIB_KIO = -lkio
LIB_KPARTS = -lkparts
LIB_KSPELL = -lkspell
LIB_KSYCOCA = -lkio
LIB_QPE = 
LIB_QT = -lqt-mt  $(LIBPNG) -lXext $(LIB_X11) $(LIBSM) -lpthread
LIB_QTOPIA = @LIB_QTOPIA@
LIB_SMB = -lsmb
LIB_X11 = -lX11 $(LIBSOCKET)
LIB_XEXT = -lXext
LN_S = ln -s
MAKEINFO = makeinfo
MCOPIDL = /usr/bin/mcopidl
MEINPROC = /usr/bin/meinproc
MICO_INCLUDES = @MICO_INCLUDES@
MICO_LDFLAGS = @MICO_LDFLAGS@
MOC = /usr/share/qt3/bin/moc
MSGFMT = /usr/bin/msgfmt
NOOPT_CFLAGS = 
NOOPT_CXXFLAGS =  -fno-exceptions -fno-check-new
NOREPO = -fno-repo
OBJDUMP = @OBJDUMP@
OBJEXT = o
PACKAGE = kmd
PAMLIBS = @PAMLIBS@
PASSWDLIBS = @PASSWDLIBS@
PYTHONINC = @PYTHONINC@
PYTHONLIB = @PYTHONLIB@
PYTHONMODDIR = @PYTHONMODDIR@
QTE_NORTTI = 
QTOPIA_INCLUDES = @QTOPIA_INCLUDES@
QT_INCLUDES = -I/usr/share/qt3/include
QT_LDFLAGS = 
RANLIB = ranlib
REPO = -frepo
SETUIDFLAGS = @SETUIDFLAGS@
STRIP = strip
TOPSUBDIRS =  doc kmd po
UIC = /usr/share/qt3/bin/uic -L $(kde_widgetdir) -nounload
UIC_TR = tr2i18n
USER_INCLUDES = 
USER_LDFLAGS = 
USE_EXCEPTIONS = -fexceptions
USE_RTTI = 
USE_THREADS = 
VERSION = 0.3
WOVERLOADED_VIRTUAL = 
XGETTEXT = /usr/bin/xgettext
XPMINC = @XPMINC@
XPMLIB = @XPMLIB@
X_EXTRA_LIBS =  -lresolv
X_INCLUDES = -I/usr/X11R6/include
X_LDFLAGS = -L/usr/X11R6/lib
X_PRE_LIBS = 
all_includes = -I/usr/include/kde -I/usr/share/qt3/include -I/usr/X11R6/include 
all_libraries = -L/usr/X11R6/lib -L/usr/lib 
idldir = @idldir@
jni_includes = @jni_includes@
kde_appsdir = ${prefix}/share/applnk
kde_bindir = ${exec_prefix}/bin
kde_confdir = ${prefix}/share/config
kde_datadir = ${prefix}/share/apps
kde_htmldir = ${prefix}/share/doc/HTML
kde_icondir = ${prefix}/share/icons
kde_includes = /usr/include/kde
kde_libraries = /usr/lib
kde_libs_htmldir = /usr/share/doc/kde/HTML
kde_libs_prefix = /usr
kde_locale = ${prefix}/share/locale
kde_mimedir = ${prefix}/share/mimelnk
kde_moduledir = ${exec_prefix}/lib/kde3
kde_qtver = 3
kde_servicesdir = ${prefix}/share/services
kde_servicetypesdir = ${prefix}/share/servicetypes
kde_sounddir = ${prefix}/share/sounds
kde_styledir = ${exec_prefix}/lib/kde3/plugins/styles
kde_templatesdir = ${prefix}/share/templates
kde_wallpaperdir = ${prefix}/share/wallpapers
kde_widgetdir = ${exec_prefix}/lib/kde3/plugins/designer
micodir = @micodir@
qt_includes = /usr/share/qt3/include
qt_libraries = 
x_includes = /usr/X11R6/include
x_libraries = /usr/X11R6/lib

kde_module_LTLIBRARIES = kio_kmd.la

INCLUDES = $(all_includes)

LDFLAGS = 

#>- kio_kmd_la_METASOURCES = AUTO

kio_kmd_la_SOURCES = kmd.cpp 
kio_kmd_la_LIBADD = $(LIB_KIO) $(LIB_KDEUI) $(LIB_KDECORE) $(LIB_QT)

kio_kmd_la_LDFLAGS = $(all_libraries) -module $(KDE_PLUGIN)    

EXTRA_DIST = kmd.cpp kmd.h kmd.protocol 
mkinstalldirs = $(SHELL) $(top_srcdir)/admin/mkinstalldirs
CONFIG_HEADER = ../config.h
CONFIG_CLEAN_FILES = 
LTLIBRARIES =  $(kde_module_LTLIBRARIES)


DEFS = -DHAVE_CONFIG_H -I. -I$(srcdir) -I..
CPPFLAGS =  -DQT_THREAD_SUPPORT  -D_REENTRANT
LIBS = 
kio_kmd_la_DEPENDENCIES = 
#>- kio_kmd_la_OBJECTS =  kmd.lo
#>+ 6
kio_kmd_la_final_OBJECTS = kio_kmd_la.all_cpp.lo 
kio_kmd_la_nofinal_OBJECTS = kmd.lo\
	kmd.moc.lo  \
	kio_kmd_la_meta_unload.lo 
kio_kmd_la_OBJECTS = $(kio_kmd_la_nofinal_OBJECTS)
#kio_kmd_la_OBJECTS = $(kio_kmd_la_final_OBJECTS)
CXXFLAGS = -O2 -fno-exceptions -fno-check-new
#>- CXXCOMPILE = $(CXX) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
#>+ 1
CXXCOMPILE = $(CXX) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) $(KDE_CXXFLAGS)
#>- LTCXXCOMPILE = $(LIBTOOL) --mode=compile $(CXX) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
#>+ 1
LTCXXCOMPILE = $(LIBTOOL) --mode=compile --tag=CXX $(CXX) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) $(KDE_CXXFLAGS)
CXXLD = $(CXX)
#>- CXXLINK = $(LIBTOOL) --mode=link $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(LDFLAGS) -o $@
#>+ 1
CXXLINK = $(LIBTOOL) --mode=link --tag=CXX $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(KDE_CXXFLAGS) $(LDFLAGS) -o $@
DIST_COMMON =  Makefile.am Makefile.in


#>- DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)
#>+ 4
KDE_DIST=kio_kmd.la.closure 

DISTFILES= $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST) $(KDE_DIST)


TAR = gtar
GZIP_ENV = --best
SOURCES = $(kio_kmd_la_SOURCES)
OBJECTS = $(kio_kmd_la_OBJECTS)

#>- all: all-redirect
#>+ 1
all: docs-am  all-redirect
.SUFFIXES:
.SUFFIXES: .S .c .cpp .lo .o .obj .s
$(srcdir)/Makefile.in: Makefile.am $(top_srcdir)/configure.in $(ACLOCAL_M4) 
#>- 	cd $(top_srcdir) && $(AUTOMAKE) --gnu --include-deps kmd/Makefile
#>+ 2
	cd $(top_srcdir) && $(AUTOMAKE) --gnu --include-deps kmd/Makefile
	cd $(top_srcdir) && perl admin/am_edit kmd/Makefile.in

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) \
	&& CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status


mostlyclean-kde_moduleLTLIBRARIES:

clean-kde_moduleLTLIBRARIES:
	-test -z "$(kde_module_LTLIBRARIES)" || rm -f $(kde_module_LTLIBRARIES)

distclean-kde_moduleLTLIBRARIES:

maintainer-clean-kde_moduleLTLIBRARIES:

install-kde_moduleLTLIBRARIES: $(kde_module_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(kde_moduledir)
	@list='$(kde_module_LTLIBRARIES)'; for p in $$list; do \
	if test -f $$p; then \
	echo "$(LIBTOOL)  --mode=install $(INSTALL) $$p $(DESTDIR)$(kde_moduledir)/$$p"; \
	$(LIBTOOL)  --mode=install $(INSTALL) $$p $(DESTDIR)$(kde_moduledir)/$$p; \
	else :; fi; \
	done

uninstall-kde_moduleLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	list='$(kde_module_LTLIBRARIES)'; for p in $$list; do \
	$(LIBTOOL)  --mode=uninstall rm -f $(DESTDIR)$(kde_moduledir)/$$p; \
	done

.c.o:
	$(COMPILE) -c $<

# FIXME: We should only use cygpath when building on Windows,
# and only if it is available.
.c.obj:
	$(COMPILE) -c `cygpath -w $<`

.s.o:
	$(COMPILE) -c $<

.S.o:
	$(COMPILE) -c $<

mostlyclean-compile:
	-rm -f *.o core *.core
	-rm -f *.$(OBJEXT)

clean-compile:

distclean-compile:
	-rm -f *.tab.c

maintainer-clean-compile:

.c.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

.s.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

.S.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:

maintainer-clean-libtool:

#>- kio_kmd.la: $(kio_kmd_la_OBJECTS) $(kio_kmd_la_DEPENDENCIES)
#>+ 2
kio_kmd.la: kio_kmd.la.closure $(kio_kmd_la_OBJECTS) $(kio_kmd_la_DEPENDENCIES)
#kio_kmd.la: $(kio_kmd_la_OBJECTS) $(kio_kmd_la_DEPENDENCIES)
	$(CXXLINK) -rpath $(kde_moduledir) $(kio_kmd_la_LDFLAGS) $(kio_kmd_la_OBJECTS) $(kio_kmd_la_LIBADD) $(LIBS)
.cpp.o:
	$(CXXCOMPILE) -c $<
.cpp.obj:
	$(CXXCOMPILE) -c `cygpath -w $<`
.cpp.lo:
	$(LTCXXCOMPILE) -c $<

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP)
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	awk '    { files[$$0] = 1; } \
	END { for (i in files) print i; }'`; \
	here=`pwd` && cd $(srcdir) \
	&& mkid -f$$here/ID $$unique $(LISP)

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	awk '    { files[$$0] = 1; } \
	END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	|| (cd $(srcdir) && etags $(ETAGS_ARGS) $$tags  $$unique $(LISP) -o $$here/TAGS)

mostlyclean-tags:

clean-tags:

distclean-tags:
	-rm -f TAGS ID

maintainer-clean-tags:

distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

subdir = kmd

distdir: $(DISTFILES)
	@for file in $(DISTFILES); do \
	d=$(srcdir); \
	if test -d $$d/$$file; then \
	cp -pr $$d/$$file $(distdir)/$$file; \
	else \
	test -f $(distdir)/$$file \
	|| ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	|| cp -p $$d/$$file $(distdir)/$$file || :; \
	fi; \
	done
kio_kmd_la_meta_unload.lo kio_kmd_la_meta_unload.o : \
	kio_kmd_la_meta_unload.cpp
kmd.moc.lo kmd.moc.o : kmd.moc.cpp kmd.h
kmd.lo kmd.o : kmd.cpp kmd.h

info-am:
info: info-am
dvi-am:
dvi: dvi-am
check-am: all-am
check: check-am
installcheck-am:
installcheck: installcheck-am
#>- install-exec-am:
#>+ 1
install-exec-am: install-kde_moduleLTLIBRARIES
install-exec: install-exec-am

#>- install-data-am: install-kde_moduleLTLIBRARIES install-data-local
#>+ 1
install-data-am:  install-data-local
install-data: install-data-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
install: install-am
uninstall-am: uninstall-kde_moduleLTLIBRARIES uninstall-local
uninstall: uninstall-am
all-am: Makefile $(LTLIBRARIES)
all-redirect: all-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) AM_INSTALL_PROGRAM_FLAGS=-s install
installdirs:
	$(mkinstalldirs)  $(DESTDIR)$(kde_moduledir)


mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*

maintainer-clean-generic:
mostlyclean-am:  mostlyclean-kde_moduleLTLIBRARIES mostlyclean-compile \
	mostlyclean-libtool mostlyclean-tags \
	mostlyclean-generic

mostlyclean: mostlyclean-am

#>- clean-am:  clean-kde_moduleLTLIBRARIES clean-compile clean-libtool \
#>- clean-tags clean-generic mostlyclean-am
#>+ 2
clean-am: clean-metasources clean-closures clean-moc-classes clean-final   clean-kde_moduleLTLIBRARIES clean-compile clean-libtool \
	clean-tags clean-generic mostlyclean-am

#>- clean: clean-am
#>+ 1
clean: kde-rpo-clean  clean-am

distclean-am:  distclean-kde_moduleLTLIBRARIES distclean-compile \
	distclean-libtool distclean-tags distclean-generic \
	clean-am
	-rm -f libtool

distclean: distclean-am

maintainer-clean-am:  maintainer-clean-kde_moduleLTLIBRARIES \
	maintainer-clean-compile maintainer-clean-libtool \
	maintainer-clean-tags maintainer-clean-generic \
	distclean-am
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

maintainer-clean: maintainer-clean-am

.PHONY: mostlyclean-kde_moduleLTLIBRARIES \
	distclean-kde_moduleLTLIBRARIES clean-kde_moduleLTLIBRARIES \
	maintainer-clean-kde_moduleLTLIBRARIES uninstall-kde_moduleLTLIBRARIES \
	install-kde_moduleLTLIBRARIES mostlyclean-compile distclean-compile \
	clean-compile maintainer-clean-compile mostlyclean-libtool \
	distclean-libtool clean-libtool maintainer-clean-libtool tags \
	mostlyclean-tags distclean-tags clean-tags maintainer-clean-tags \
	distdir info-am info dvi-am dvi check check-am installcheck-am \
	installcheck install-exec-am install-exec install-data-local \
	install-data-am install-data install-am install uninstall-local \
	uninstall-am uninstall all-redirect all-am all installdirs \
	mostlyclean-generic distclean-generic clean-generic \
	maintainer-clean-generic clean mostlyclean distclean maintainer-clean


install-data-local:
#>- 	$(mkinstalldirs)  $(kde_servicesdir)/
#>+ 1
	$(mkinstalldirs)  $(DESTDIR)$(kde_servicesdir)/
#>- 	$(INSTALL_DATA) $(srcdir)/kmd.protocol  $(kde_servicesdir)/kmd.protocol
#>+ 1
	$(INSTALL_DATA) $(srcdir)/kmd.protocol  $(DESTDIR)$(kde_servicesdir)/kmd.protocol

uninstall-local:
#>- 	-rm -f  $(kde_servicesdir)/kmd.protocol
#>+ 1
	-rm -f  $(DESTDIR)$(kde_servicesdir)/kmd.protocol

####### kdevelop will overwrite this part!!! (end)############
# These paths are KDE specific. Use them:
# kde_appsdir         Where your application's menu entry (.desktop) should go to.
# kde_icondir         Where your icon should go to - better use KDE_ICON.
# kde_sounddir        Where your sounds should go to.
# kde_htmldir         Where your docs should go to. (contains lang subdirs)
# kde_datadir         Where you install application data. (Use a subdir)
# kde_locale          Where translation files should go to. (contains lang subdirs)
# kde_cgidir          Where cgi-bin executables should go to.
# kde_confdir         Where config files should go to (system-wide ones with default values).
# kde_mimedir         Where mimetypes .desktop files should go to.
# kde_servicesdir     Where services .desktop files should go to.
# kde_servicetypesdir Where servicetypes .desktop files should go to.
# kde_toolbardir      Where general toolbar icons should go to (deprecated, use KDE_ICON).
# kde_wallpaperdir    Where general wallpapers should go to.
# kde_templatesdir    Where templates for the "New" menu (Konqueror/KDesktop) should go to.
# kde_bindir          Where executables should go to. Use bin_PROGRAMS or bin_SCRIPTS.
# kde_libdir          Where shared libraries should go to. Use lib_LTLIBRARIES.
# kde_moduledir       Where modules (e.g. parts) should go to. Use kde_module_LTLIBRARIES.
# kde_styledir        Where Qt/KDE widget styles should go to (new in KDE 3).
# kde_designerdir     Where Qt Designer plugins should go to (new in KDE 3).

# make messages.po. Move this one to ../po/ and "make merge" in po
# the -x is for skipping messages already translated in kdelibs
messages:
	LIST=`find . -name \*.h -o -name \*.hh -o -name \*.H -o -name \*.hxx -o -name \*.hpp -o -name \*.cpp -o -name \*.cc -o -name \*.cxx -o -name \*.ecpp -o -name \*.C`; \
	if test -n "$$LIST"; then \
	$(XGETTEXT) -C -ki18n -x $(kde_includes)/kde.pot $$LIST -o ../po/kmd.pot; \
	fi

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:

#>+ 8
kio_kmd.la.closure: $(kio_kmd_la_OBJECTS) $(kio_kmd_la_DEPENDENCIES)
	@echo "int main() {return 0;}" > kio_kmd_la_closure.cpp
	@$(LTCXXCOMPILE) -c kio_kmd_la_closure.cpp
	$(CXXLINK) kio_kmd_la_closure.lo $(kio_kmd_la_LDFLAGS) $(kio_kmd_la_OBJECTS) $(kio_kmd_la_LIBADD) $(LIBS)
	@rm -f kio_kmd_la_closure.* kio_kmd.la.closure
	@echo "timestamp" > kio_kmd.la.closure


#>+ 3
kmd.moc.cpp: $(srcdir)/kmd.h
	$(MOC) $(srcdir)/kmd.h -o kmd.moc.cpp

#>+ 3
clean-metasources:
	-rm -f  kmd.moc.cpp

#>+ 3
clean-closures:
	-rm -f  kio_kmd.la.closure

#>+ 2
docs-am:

#>+ 5
force-reedit:
		cd $(top_srcdir) && $(AUTOMAKE) --gnu --include-deps kmd/Makefile
	cd $(top_srcdir) && perl admin/am_edit kmd/Makefile.in


#>+ 12
kio_kmd_la_meta_unload.cpp:  kmd.moc.cpp
	@echo 'creating kio_kmd_la_meta_unload.cpp'
	@-rm -f kio_kmd_la_meta_unload.cpp
	@if test ${kde_qtver} = 2; then \
		echo 'static const char * _metalist_kio_kmd_la[] = {' > kio_kmd_la_meta_unload.cpp ;\
		cat  kmd.moc.cpp | grep 'char.*className' | sed -e 's/.*[^A-Za-z0-9_:]\([A-Za-z0-9_:]*\)::className.*$$/\"\1\",/' | sort | uniq >> kio_kmd_la_meta_unload.cpp ;\
		echo '0};' >> kio_kmd_la_meta_unload.cpp ;\
		echo '#include <kunload.h>' >> kio_kmd_la_meta_unload.cpp ;\
		echo '_UNLOAD(kio_kmd_la)' >> kio_kmd_la_meta_unload.cpp ;\
	else echo > kio_kmd_la_meta_unload.cpp; fi


#>+ 3
clean-moc-classes:
	-rm -f  kio_kmd_la_meta_unload.cpp

#>+ 11
kio_kmd_la.all_cpp.cpp: $(srcdir)/Makefile.in $(srcdir)/kmd.cpp kio_kmd_la_meta_unload.cpp  kmd.moc.cpp
	@echo 'creating kio_kmd_la.all_cpp.cpp ...'; \
	rm -f kio_kmd_la.all_cpp.files kio_kmd_la.all_cpp.final; \
	echo "#define KDE_USE_FINAL 1" >> kio_kmd_la.all_cpp.final; \
	for file in kmd.cpp kio_kmd_la_meta_unload.cpp  kmd.moc.cpp; do \
	  echo "#include \"$$file\"" >> kio_kmd_la.all_cpp.files; \
	  test ! -f $(srcdir)/$$file || egrep '^#pragma +implementation' $(srcdir)/$$file >> kio_kmd_la.all_cpp.final; \
	done; \
	cat kio_kmd_la.all_cpp.final kio_kmd_la.all_cpp.files  > kio_kmd_la.all_cpp.cpp; \
	rm -f kio_kmd_la.all_cpp.final kio_kmd_la.all_cpp.files

#>+ 3
clean-final:
	-rm -f kio_kmd_la.all_cpp.cpp

#>+ 2
final:
	$(MAKE) kio_kmd_la_OBJECTS="$(kio_kmd_la_final_OBJECTS)" all-am
#>+ 2
final-install:
	$(MAKE) kio_kmd_la_OBJECTS="$(kio_kmd_la_final_OBJECTS)" install-am
#>+ 2
no-final:
	$(MAKE) kio_kmd_la_OBJECTS="$(kio_kmd_la_nofinal_OBJECTS)" all-am
#>+ 2
no-final-install:
	$(MAKE) kio_kmd_la_OBJECTS="$(kio_kmd_la_nofinal_OBJECTS)" install-am
#>+ 3
cvs-clean:
	$(MAKE) -f $(top_srcdir)/admin/Makefile.common cvs-clean

#>+ 3
kde-rpo-clean:
	-rm -f *.rpo
